
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-phillebaba-io-v1alpha1-generatedsecret
  failurePolicy: Fail
  name: mgeneratedsecret.kb.io
  rules:
  - apiGroups:
    - core.phillebaba.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - generatedsecrets
