apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: controller-manager
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    app: kubernetes-generated-secret
