# permissions to do viewer generatedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: generatedsecret-viewer
rules:
- apiGroups:
  - core.phillebaba.io
  resources:
  - generatedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.phillebaba.io
  resources:
  - generatedsecrets/status
  verbs:
  - get
