# permissions to do edit generatedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: generatedsecret-editor
rules:
- apiGroups:
  - core.phillebaba.io
  resources:
  - generatedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.phillebaba.io
  resources:
  - generatedsecrets/status
  verbs:
  - get
  - patch
  - update
