apiVersion: core.phillebaba.io/v1alpha1
kind: GeneratedSecret
metadata:
  name: generatedsecret-sample
spec:
  data:
  - key: test
    length: 100
    options:
      - Uppercase
      - Lowercase
      - Numbers
      - Symbols
